spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library?serverTimezone=GMT%2b8
    username: root
    password: qazwsx123
mybatis:
  type-aliases-package: org.fogsky.library.model
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml
server:
  servlet:
    context-path: /library
user:
  nameSize:    用户名应为2至10位
  passwordSize: 密码应为6至25位数